# Curso Deep Learning - Exercício pré-curso NumPy

Este é um notebook Jupyter contendo exercícios de programação matricial utilizando o Python e biblioteca NumPy.
Estes exercícios servem para verificar os conhecimentos da linguagem Python para manipulação matricial com a biblioteca NumPy.

Esta lista de exercício é um guia de estudo. Para fazer os exercícios será necessário estudar o NumPy e consultar documentação e tutoriais disponíveis na Internet.

### Python

Recomenda-se utilizar o Google Colab para fazer esses exercícios (https://colab.research.google.com/). A vantagem do Colab é ser uma plataforma gratuito que permite o uso de GPU, fundamental para a realização dos exercícios de deep learning.


### Jupyter notebook

Este é um Notebook Jupyter. Um notebook Jupyter é uma mistura de linguagem Markdown para formatar texto (como uma Wiki) e um programa Python. É muito usado entre as pessoas que trabalham com Data Science e Machine Learning em Python.


Você pode adicionar quantas células quiser neste notebook para deixar suas respostas bem organizadas.

# Exercícios usando NumPy

Os seguintes exercícios devem usar apenas o pacote NumPy.
Não se deve utilizar nenhum outro pacote adicional.
O NumPy é o pacote que faz o Python apropriado para programação científica.
A programação eficiente de matrizes multidimensionais (arrays ou tensores) é
feita através do conceito de programação matricial que evita o uso de laços
e iterações nos elementos da matriz.

Existem vários exemplos de uso de NumPy no conjunto de
notebooks tutorias disponíveis no GitHub:
- https://github.com/robertoalotufo/ia898/blob/master/master/0_index.ipynb

## Preencha o seu nome

In [ ]:
print('Meu nome é: XXXXX')

Meu nome é: XXXXX


In [ ]:
import numpy as np

Veja como é possível criar um array unidimensional e depois reformatá-lo para ser acessado como array bidimensional:

In [ ]:
array = np.arange(10)
print(array)
print(array.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [ ]:
A = np.arange(24).reshape(4, 6)
print(A)
print(A.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


### Exercício: imprimindo rows, cols, dimensions, shape and datatype

In [ ]:
# imprima o número de linhas de A
print()
# imprima o número de colunas de A
print()
# imprima o número de dimensões de A
print()
# imprima o shape de A:
print()
# imprima o tipo de dados (dtype) dos elementos de A:
print()

### Reshape

In [ ]:
# Seja o vetor unidimensional a:
a = np.array([1, 2, 3, 4])
print(a, a.shape)

[1 2 3 4] (4,)


### Exercício: Converta o vetor unidimensional a em uma matriz vetor coluna (4 linhas e 1 coluna) utilizando reshape

In [ ]:
a = a  # Escreva código aqui.
print(a)

[1 2 3 4]


## Exercício: Cópia por referência, cópia rasa e cópia profunda

Explique a diferença entre estes 3 tipos de cópias e dê um exemplo de cada uma.
Atenção, o conceito aqui é em relação ao NumPy e não ao Python.
**Resposta**:


In [ ]:
# Indique para cada uma das expressões a seguir se a cópia é por referência, rasa ou profunda
x = a # cópia ?
y = a[:2] # cópia ?
z = a.reshape(4, 1) # cópia ?
zz = a.copy() # cópia ?

In [ ]:
# Explique o valor dos resultados:
z[0,0] = 5
print(a) # explique:
y[1] = 6
print(a) # explique:
zz[0] = 7
print(a) # explique:

[5 2 3 4]
[5 6 3 4]
[5 6 3 4]


## Operações aritméticas

In [ ]:
B = A + 10
B

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33]])

### Array binário (booleano)

#### Exercício: Crie uma matriz booleana C com True nos elementos de B menores que 18 (não utilize loop explícito)

In [ ]:
C = B  # Modifique o código aqui.
print(C)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]]


## Indexação booleana

### Exercício: explique o comando a seguir de indexação booleana

In [ ]:
A[B < 18]

array([0, 1, 2, 3, 4, 5, 6, 7])

Explicação:

Veja um programa que cria matriz D_loop a partir da matriz B, porém trocando os elementos menores que 18 por seus valores negativos

In [ ]:
D_loop = B.copy()
for row in np.arange(B.shape[0]):
    for col in np.arange(B.shape[1]):
        if B[row,col] < 18:
            D_loop[row,col] = - B[row,col]
print(D_loop)

[[-10 -11 -12 -13 -14 -15]
 [-16 -17  18  19  20  21]
 [ 22  23  24  25  26  27]
 [ 28  29  30  31  32  33]]


### Exercício: Substitua o programa acima por uma única linha sem loop, utilizando indexação booleana e evitando o uso de `where`

In [ ]:
D = B   # << modifique aqui utilizando indexação booleana
print(D)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]]


### Exercício: Teste sua solução neste outro exemplo:

In [ ]:
np.random.seed(55)
B_test = np.random.randint(-17,33,(4,6))
print(B_test)

[[ -4   9  22  -9  12  20]
 [ 20  10  16  31  18  29]
 [ 13  -4  13  -5   7  30]
 [-10  14  16  -9  -7  12]]


## Redução de eixo: soma

Operações matriciais de redução de eixo são muito úteis e importantes.
É um conceito importante da programação matricial.

Estude o exemplo a seguir:

In [ ]:
print(A)
print(A.shape)
As = A.sum(axis=0)
print(As)
print(As.shape)

### Exercício: Explique o funcionamento da soma por redução de eixo. Qual foi a dimensão que desapareceu?

Resposta: 

### Exercício: calcule o valor médio do array A

In [ ]:
print()

### Exercício: calcule o valor médio das linhas de A:

In [ ]:
print()

## Broadcasting

### Exercício: O que significa o conceito de broadcasting em NumPy?

Resposta:

### Exercício: Usando o conceito de broadcast, mude o shape do vetor a para que o broadcast possa ocorrer quando fizermos G = A + a

In [ ]:
a = np.arange(4)
print(a)
#G = A + a
#print(G)

## Normalização entre 0 e 1

Seja a matriz $C$ que é a normalização da matriz $A$:
$$ C(i,j) = \frac{A(i,j) - A_{min}}{A_{max} - A_{min}} $$

Em programação matricial, não se faz o loop em cada elemento da matriz,
mas sim, utiliza-se operações matriciais. Faça o exercício a seguir
sem utilizar laços explícitos:

### Exercício: Criar a matriz C que é a normalização de A, de modo que os valores de C estejam entre 0 e 1.


In [ ]:
C = A
print(C)

### Exercício: Modificar o exercício anterior, porém agora faça a normalização para cada coluna de A de modo que as colunas da matriz D estejam entre os valores de 0 a 1. Utilize o conceito de redução de eixo.


In [ ]:
D = A
print(D)

### Exercício: Modificar o exercício anterior, porém agora faça a normalização para cada linha de A de modo que as colunas da matriz E estejam entre os valores de 0 a 1. Atenção: sua solução deve funcionar para qualquer matriz, de tamanhos diversos. Utilize o conceito de redução de eixo, porém mantenha o mesmo número de eixos para poder fazer broadcast.

In [ ]:
E = A
print(E)

## Fatiamento em arrays (slicing)

In [ ]:
# esta indexação é chamada fatiamento:
AA = A[:,1::2]
print(AA)

### Exercício: Crie a matriz AB apenas com as linhas pares da matriz A, utilizando o conceito de fatiamento:


In [ ]:
AB = A
print(AB)

### Exercicío: Crie a matriz AC com mesmo shape da matriz A, porém com os elementos na ordem inversa, ou seja, trocando a ordem das linhas e das colunas.



Por exemplo, a matriz [[1, 2, 3], [4, 5, 6]] será transformada para [[6, 5, 4], [3, 2, 1]]

In [ ]:
AC = A
print(AC)

## Produto matricial  (dot product)

### Exercício: Calcule a matriz E dada pelo produto matricial entre a matriz A e sua transposta: 
$$ E = A A^T $$

In [ ]:
E = A # modify your code here
print(E)

### Exercício: Descomente a linha e explique por que a operação de multiplicação dá erro.

In [ ]:
#Ee = A * A.T

## Matrizes multidimensionais

Em deep learning, iremos utilizar matrizes multidimensionais
que são denominados como arrays no NumPy. PyTorch usa o nome de tensor para
suas matrizes multimensionais.

Matrizes de dimensões maior que 4 são de difícil intuição. A melhor forma de lidar
com elas é observando o seu *shape*.

### 3-D array

In [ ]:
F = A.reshape(2, 3, 4)
print(F)

#### Indexação

Estude as seguintes indexações:

In [ ]:
F1 = F[1]
print(F1)
F2 = F[1,0,:]
print(F2)
F3 = F[1,0,2]
print(F3)
F4 = F[1:2,0,2]
print(F4)

In [ ]:
print(F1.shape)
print(F2.shape)
print(F3.shape)
print(F4.shape)

### Exercício: Explique as dimensões de cada array:

F1:

F2:

F3:

F4:

## Redução de eixo - aplicado a dois eixos simultâneos

Redução de eixo é quando a operação matricial resulta num array de menores dimensões.
Com essas operações, calcula-se estatística de colunas, linhas, etc.

### Exercício: Calcule o valor médio das matrizes F[0] e F[1], utilizando o conceito de redução de eixo e com apenas um único comando F.mean(??). Preencha o ?? que falta entre parêntesis.

In [ ]:
print()

## Function - split - dados treino e validação

O exercício a seguir é para separar um conjunto de dados (dataset) em dois conjuntos, um
de treinamento e outro de validação.


Defina uma função que receba como entrada uma matriz, (dataset), onde cada linha é
referente a uma amostra e cada coluna referente a um atributo das amostras. O número total de
amostras é dado pelas linhas desta matriz.
Outro parâmetro de entrada é o fator de split `split_factor`, que é um número real entre 0 e 1. 
A saída da função são duas matrizes: amostras de treinamento e amostras de validação. 
A matriz de treinamento contrá o número de linhas dado por `split_factor` vezes o número de amostras.
A matriz de validação conterá o restante das amostras.

In [ ]:
# Entrada, matriz contendo 10 amostras e 9 atributos
aa = np.arange(90).reshape(10,9)
print(aa)

In [ ]:
# Saída da função t,v = split(aa, 0.8)  # utilizado split_factor de 80%
t = np.arange(72).reshape(8,9)
print(t)

In [ ]:
v = np.arange(72,90).reshape(2,9)
print(v)

In [ ]:
# Evite o uso de laço explícito
# Não utilize outras bibliotecas além do NumPy
def split(dados, split_factor):
    '''
    divide a matriz dados em dois conjuntos:
    matriz train: split_factor * n. de linhas de dados
    matriz val: (1-split_factor) * n. de linhas de dados
    parametros entrada:
        dados: matriz de entrada
        split_factor: entre 0. e 1. - fator de divisão em duas matrizes
    parametros de saída:
        train : matriz com as linhas iniciais de dados
        val: matriz com as linhas restantes
    '''
    # insert your code here
    train = val = 0
    return train, val

t,v = split(aa, 0.8)
print('t=\n', t)
print('v=\n', v)

### Exercício: Teste sua função com outros valores

# Fim do Notebook